# Use an official Node runtime as a parent image
FROM node:20-alpine

# Set the working directory
WORKDIR /app

# Copy package.json and package-lock.json
COPY frontend/package*.json ./frontend/

# Install dependencies
RUN cd frontend && npm install

# Copy the rest of the application code
COPY frontend/ ./frontend/

# Build the React app
RUN cd frontend && npm run build

# Expose the build directory as a volume
VOLUME /app/frontend/build