version: '3.8'

services:
  db:
    image: postgres:15
    volumes:
      - postgres_data:/var/lib/postgresql/data/
      - ./postgresql_entrypoint.sh:/docker-entrypoint-initdb.d/postgresql_entrypoint.sh

    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD} 
    #entrypoint: ["/docker-entrypoint-initdb.d/postgresql_entrypoint.sh"]


  web:
    build:
      context: ./
      dockerfile: Dockerfile
    command: cd backend && gunicorn backend.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - .:/app
      - static_volume:/app/backend/static  # Mount for static files
      - media_volume:/app/backend/media  # Mount for media files
    expose:
      - 8000
    depends_on:
      - db
    environment:
      - DATABASE_URL=postgres://${DB_USER}:${DB_PASSWORD}@db/{$DB_NAME}
    env_file:
      - .env

  nginx:
    build: ./nginx
    volumes:
      - static_volume:/app/static  
      - media_volume:/app/media  
    ports:
      - "80:80"
    depends_on:
      - web

volumes:
  postgres_data:
  static_volume:
  media_volume:
