# Generated by Django 5.0.7 on 2024-07-18 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('cuisine', models.CharField(max_length=50)),
                ('ingredients', models.TextField(help_text='A comma-separated list of ingredients')),
                ('cook_time', models.IntegerField(help_text='Expected time in minutes to complete the recipe')),
                ('rating', models.FloatField()),
                ('instructions', models.TextField(max_length=500)),
                ('summary', models.TextField(max_length=200)),
            ],
        ),
    ]
