# Generated by Django 5.0.7 on 2024-07-20 01:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0003_recipe_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='rating',
            field=models.FloatField(default=0),
        ),
    ]
