name: Deploy Django App to EC2 with Docker

on:
  push:
    branches:
      - main  # or the branch you want to deploy from
    paths:
      - 'backend/**'

jobs:  
  deploy-backend:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
    
    - name: Deploy to EC2
      env:
        EC2_SSH_PRIVATE_KEY: ${{ secrets.EC2_SSH_KEY }}
        EC2_SSH_HOST: ${{ secrets.EC2_SSH_HOST }}
        EC2_SSH_USERNAME: ${{ secrets.EC2_SSH_USERNAME }}
      run: |
        echo "${EC2_SSH_PRIVATE_KEY}" > private_key.pem
        chmod 600 private_key.pem
        ssh -o StrictHostKeyChecking=no -i private_key.pem $EC2_SSH_USERNAME@$EC2_SSH_HOST << 'EOF'

          # Install Docker
          if ! [ -x "$(command -v docker)" ]; then
          curl -fsSL https://get.docker.com -o get-docker.sh
          sh get-docker.sh
          sudo usermod -aG docker $USER
          fi

          # Install Docker Compose
          if ! [ -x "$(command -v docker-compose)" ]; then
          sudo curl -L "https://github.com/docker/compose/releases/download/1.29.2/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
          sudo chmod +x /usr/local/bin/docker-compose
          fi

          # Clone the repository
          if [ ! -d "Roulettech-Take-Home-App" ]; then
            git clone https://github.com/lucas-cancio/Roulettech-Take-Home-App.git
          fi

          # Pull the latest changes
          git fetch
          git reset origin/main --hard

          # Create .env file with necessary environment variables
          cd backend/  
          echo "DEBUG=False" > .env
          echo "DJANGO_JWT_SECRET_KEY=django-insecure-+$gbz!$%&vy^qk3$zrq08r(gg1%uf3ghsm2)q0j20ftk!yf-$!" >> .env
          echo "DB_PASSWORD=${{ secrets.DB_PASSWORD }}" >> .env
          echo "DB_NAME=rouletterecipe" >> .env
          echo "DB_USER=lucascancio" >> .env
          echo "DB_HOST=localhost" >> .env
          echo "DB_PORT=5432" >> .env
          echo "DB_ENGINE=django.db.backends.postgresql" >> .env

          # Pull the latest Docker image and run Docker Compose
          docker-compose down
          docker compose build
          docker-compose up -d
        EOF

        rm private_key.pem