name: Deploy React App to S3 with Docker

on:
  push:
    branches:
      - main  # or the branch you want to deploy from

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build Docker image
      run: docker build -t my-react-app -f frontend/DockerFile .

    - name: Run Docker container and copy build files
      run: |
        docker run --name react-app my-react-app
        docker cp react-app:/app/frontend/build ./build
        docker rm -f react-app

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1  # specify your AWS region

    - name: Deploy to S3
      run: aws s3 sync build/ ${{secrets.S3_BUCKET_NAME}} --delete
      #s3://your-s3-bucket-name
